<template>
  <div>
    <div class="page-head">
      <div><span class="eyebrow">OPERATIONS KNOWLEDGE BASE</span><h2>企业运维知识库</h2><p>把公司的特殊规则、SOP 和故障手册交给数字员工，分析与对话都会优先遵循这里的知识。</p></div>
      <div><input ref="fileInput" class="hidden-input" type="file" accept=".md,.txt,.pdf,.docx,.yaml,.yml,.json,.log" @change="onFileChange" /><el-button v-perm="'knowledge:write'" type="primary" :loading="uploading" @click="fileInput?.click()"><el-icon><Upload /></el-icon> 上传运维文档</el-button></div>
    </div>
    <div class="knowledge-stats"><div><strong>{{ documents.length }}</strong><span>已收录文档</span></div><div><strong>{{ tagCount }}</strong><span>规则标签</span></div><div><strong>{{ analyzedCount }}</strong><span>AI 已分析</span></div><div class="tip"><el-icon><InfoFilled /></el-icon><span>支持 PDF / DOCX / Markdown / TXT / YAML / JSON</span></div></div>
    <el-card class="search-card" shadow="never"><el-input v-model="query" clearable placeholder="搜索公司规则、故障关键词、服务名称..." @keyup.enter="search"><template #prefix><el-icon><Search /></el-icon></template></el-input><el-button @click="search">检索知识</el-button></el-card>
    <div class="knowledge-layout">
      <el-card class="docs-card" shadow="never"><template #header><div class="card-title"><span>已上传文档</span><small>按更新时间排序</small></div></template><el-table :data="documents" v-loading="loading" empty-text="还没有上传企业运维文档"><el-table-column label="文档" min-width="230"><template #default="{ row }"><div class="doc-title"><span class="file-icon"><el-icon><Document /></el-icon></span><div><strong>{{ row.title }}</strong><small>{{ row.filename }} · {{ formatSize(row.size_bytes) }}</small></div></div></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 'analyzed' ? 'success' : 'info'" size="small">{{ row.status === 'analyzed' ? 'AI 已分析' : '已入库' }}</el-tag></template></el-table-column><el-table-column label="标签" min-width="200"><template #default="{ row }"><el-tag v-for="tag in row.tags || []" :key="tag" size="small" effect="plain" class="tag">{{ tag }}</el-tag><span v-if="!row.tags?.length" class="muted">暂无标签</span></template></el-table-column><el-table-column label="摘要" min-width="260" show-overflow-tooltip prop="summary" /><el-table-column label="操作" width="78" fixed="right"><template #default="{ row }"><el-button v-perm="'knowledge:write'" link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></el-card>
      <el-card class="hits-card" shadow="never"><template #header><div class="card-title"><span>检索命中</span><small>{{ hits.length ? `共 ${hits.length} 条` : '输入关键词开始检索' }}</small></div></template><div v-if="hits.length" class="hit-list"><div v-for="hit in hits" :key="hit.id" class="hit"><div class="hit-top"><strong>{{ hit.title }}</strong><el-tag size="small" effect="plain">{{ hit.source === 'uploaded' ? '企业文档' : '内置手册' }}</el-tag></div><p>{{ hit.snippet }}</p></div></div><el-empty v-else description="暂无检索结果" :image-size="64" /></el-card>
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { deleteKnowledgeDocument, fetchKnowledgeDocuments, searchKnowledge, uploadKnowledgeDocument } from '../api'

const fileInput = ref(null); const documents = ref([]); const hits = ref([]); const query = ref(''); const loading = ref(false); const uploading = ref(false)
const analyzedCount = computed(() => documents.value.filter((item) => item.status === 'analyzed').length)
const tagCount = computed(() => new Set(documents.value.flatMap((item) => item.tags || [])).size)
function formatSize(bytes) { if (!bytes) return '0 B'; if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB` }
async function load() { loading.value = true; try { documents.value = (await fetchKnowledgeDocuments()).data.items } finally { loading.value = false } }
async function reload() { try { await load() } catch (error) { ElMessage.error(error.response?.data?.detail || '知识文档加载失败') } }
async function search() { try { hits.value = (await searchKnowledge(query.value)).data.items } catch (error) { ElMessage.error(error.response?.data?.detail || '检索失败') } }
async function onFileChange(event) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; uploading.value = true; try { const result = (await uploadKnowledgeDocument(file)).data; await load(); ElMessage.success(result.analysis?.ai_analyzed ? '文档上传并完成 AI 分析' : '文档上传成功，已建立检索索引') } catch (error) { ElMessage.error(error.response?.data?.detail || '上传失败') } finally { uploading.value = false } }
async function remove(row) { try { await ElMessageBox.confirm(`确定删除「${row.title}」吗？`, '删除知识文档', { type: 'warning' }); await deleteKnowledgeDocument(row.id); await load(); ElMessage.success('文档已删除') } catch (error) { if (error !== 'cancel') ElMessage.error(error.response?.data?.detail || '删除失败') } }
onMounted(reload)
</script>

<style scoped>
.page-head { display: flex; align-items: flex-end; justify-content: space-between; gap: 20px; margin-bottom: 22px; }.eyebrow { color: var(--brand); font-size: 11px; letter-spacing: .14em; }.page-head h2 { margin: 6px 0; font-size: 28px; }.page-head p { margin: 0; color: var(--muted); }.hidden-input { display: none; }.knowledge-stats { display: grid; grid-template-columns: repeat(3, 150px) 1fr; align-items: center; gap: 14px; margin-bottom: 16px; }.knowledge-stats > div:not(.tip) { padding: 16px 18px; border: 1px solid var(--line); border-radius: var(--r-md); background: var(--surface); }.knowledge-stats strong { display: block; color: var(--brand); font-size: 25px; }.knowledge-stats span { color: var(--muted); font-size: 12px; }.knowledge-stats .tip { display: flex; align-items: center; justify-content: flex-end; gap: 8px; color: var(--muted); font-size: 13px; }.search-card { display: flex; gap: 12px; margin-bottom: 16px; }.search-card :deep(.el-input) { flex: 1; }.knowledge-layout { display: grid; grid-template-columns: minmax(0, 1.6fr) minmax(300px, .8fr); gap: 16px; }.card-title { display: flex; align-items: center; justify-content: space-between; font-weight: 600; }.card-title small { color: var(--muted); font-size: 12px; font-weight: 400; }.doc-title { display: flex; align-items: center; gap: 10px; }.doc-title strong, .doc-title small { display: block; }.doc-title small { margin-top: 4px; color: var(--muted); font-size: 12px; }.file-icon { display: grid; place-items: center; width: 32px; height: 32px; border-radius: 8px; color: var(--brand); background: var(--el-color-primary-light-9); }.tag { margin: 2px 4px 2px 0; }.muted { color: var(--muted); font-size: 12px; }.hit-list { max-height: 540px; overflow: auto; }.hit { padding: 13px 0; border-bottom: 1px solid var(--line); }.hit:first-child { padding-top: 0; }.hit-top { display: flex; justify-content: space-between; align-items: center; gap: 8px; }.hit p { margin: 8px 0 0; color: var(--muted); font-size: 13px; line-height: 1.7; }.docs-card :deep(.el-card__body) { padding-top: 0; }.hits-card :deep(.el-card__body) { min-height: 340px; }
@media (max-width: 900px) { .page-head { align-items: flex-start; flex-direction: column; }.knowledge-stats { grid-template-columns: repeat(3, 1fr); }.knowledge-stats .tip { grid-column: span 3; justify-content: flex-start; }.knowledge-layout { grid-template-columns: 1fr; } }
.search-card :deep(.el-card__body) { display: flex; align-items: center; gap: 12px; width: 100%; }
</style>
